name: genai
channels:
  - pytorch
  - nvidia/label/cuda-11.6.1
  - nvidia
  - defaults
  - pip:
      - ema-pytorch==0.4.8
      - ffmpeg-python==0.2.0
      - huggingface-hub==0.23.2
      - hydra-core==1.0.7
      - imagen-pytorch==2.0.0
      - ipython==7.23.1
      - ipywidgets==8.1.3
      - librosa==0.10.2.post1
      - lightning-utilities==0.11.2
      - numpy==1.24.4
      - opencv-contrib-python==4.10.0.82
      - opencv-python==4.6.0.66
      - pandas==2.0.3
      - pillow==9.0.1
      - pytorch-lightning==1.4.5
      - tensorboard==2.14.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torchmetrics==0.5.0
      - torchvision==0.18.1
      - tqdm==4.62.3
      - transformers==4.41.2
      - video-diffusion-pytorch==0.7.0
# prefix: /home/hongn/miniconda3/envs/genai
